// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjZJnY-Gv0MrAXH9fBClyeOI5CsZfZTo',
    appId: '1:385148574959:web:51e262871cd0db658a8f1a',
    messagingSenderId: '385148574959',
    projectId: 'fir-flutter-ac78a',
    authDomain: 'fir-flutter-ac78a.firebaseapp.com',
    storageBucket: 'fir-flutter-ac78a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJYHuox2nYTbpmWoPtZ1n5EJBSpcDhvI',
    appId: '1:385148574959:ios:79e9617bf56b464b8a8f1a',
    messagingSenderId: '385148574959',
    projectId: 'fir-flutter-ac78a',
    storageBucket: 'fir-flutter-ac78a.firebasestorage.app',
    iosBundleId: 'com.flutterfirebase.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJYHuox2nYTbpmWoPtZ1n5EJBSpcDhvI',
    appId: '1:385148574959:ios:90fd967f510a4fba8a8f1a',
    messagingSenderId: '385148574959',
    projectId: 'fir-flutter-ac78a',
    storageBucket: 'fir-flutter-ac78a.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQjZJnY-Gv0MrAXH9fBClyeOI5CsZfZTo',
    appId: '1:385148574959:web:a07376a045e151008a8f1a',
    messagingSenderId: '385148574959',
    projectId: 'fir-flutter-ac78a',
    authDomain: 'fir-flutter-ac78a.firebaseapp.com',
    storageBucket: 'fir-flutter-ac78a.firebasestorage.app',
  );

}